name: 'Audit Report'
description: 'Run audit on projects and report vulnerabilities'
inputs:
    projects:
      required: true
    include-dev-dependencies:
      required: false
    include-unfixed:
      required: false
    severity-levels:
      required: true
    issue_title_prefix:
      required: false
    token:
      required: true
runs:
  using: 'node20'
  main: 'dist/index.js'