name: 'Audit Report'
description: 'Run audit on projects and report vulnerabilities'
inputs:
    projects:
      required: true
    include-dev-dependencies:
      required: true
    include-unfixed-for-image:
      required: false
    include-unfixed-for-fs:
      required: false
    severity-levels-for-image:
      required: true
    severity-levels-for-fs:
      required: true
    issue_title_prefix:
      required: false
    token:
      required: true
runs:
  using: 'node20'
  main: 'dist/index.js'