name: "Audit"
runs:
  using: "composite"
  steps:
    - id: audit
      name: Audit project ${{ matrix.project }}
      run: cd ${{ matrix.project }} && npm ci --no-audit --legacy-peer-deps && echo "result=$(npm run audit -- --production)" >> "$GITHUB_OUTPUT"
      shell: bash
  outputs:
    result: ${{ steps.audit.outputs.result }}
