name: Daily Dependency Check for vulnerabilities
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  audit: 
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.auditt.outputs }}
    strategy:
      matrix:
        node-version: [ 18.x ]
        project:
          [
            frontend,
            api,
            blockchain,
            provisioning,
            e2e-test,
            excel-export-service,
            email-notification-service,
            storage-service,
            logging-service,
            migration
          ]
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - id: auditt
        name: Audit project ${{ matrix.project }}
        run: npm ci --no-audit --legacy-peer-deps && echo "$(npm run audit -- --production)" >> "$GITHUB_OUTPUT" && echo "$GITHUB_OUTPUT"
        shell: bash
  scheduled-audit-notification:
    needs:
      - audit
    if: always()
    uses: ./.github/workflows/scheduled-audit-notification.yml
    with:
      success: ${{ needs.audit.result == 'success' }}
      result: ${{ needs.audit.outputs.result }}
